### ISSUE TITLE
Segfaults on `echo 1 > 2 | bc -l`

### ISSUE THREAD

**Issue by epruesse** [conda-forge/bc-feedstock#7]
Issue: `bc -l` segfaults (both osx and linux)

```
echo '1 > 2' | bc -l
```

Environment (<code>conda list</code>):

```
$ conda list | grep -E '^bc|^flex|^libgcc'
bc                        1.06              h14c3975_1001    conda-forge
flex                      2.6.4             hf484d3e_1004    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
```

**Comment by duncanmmacleod** [comment]
@epruesse, apologies for the delay, but `bc-1.07.1` is now available through conda-forge. Your example is now included directly in the recipe as a test, so you should be able to update to that version. Please confirm.
